# Generated by Django 3.2.6 on 2022-03-25 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_authors', models.IntegerField(null=True)),
                ('number_of_unique_authors', models.IntegerField(null=True)),
                ('number_of_books', models.IntegerField(null=True)),
                ('number_of_unique_books', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('total_word_count', models.IntegerField(null=True)),
                ('largest_book', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='authorMeta',
            fields=[
                ('author_uri', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('author_ar', models.CharField(max_length=255, null=True)),
                ('author_lat', models.CharField(max_length=255)),
                ('date', models.IntegerField(null=True)),
                ('authorDateAH', models.IntegerField(null=True)),
                ('authorDateCE', models.IntegerField(null=True)),
                ('authorDateString', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='relationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type_id', models.IntegerField(unique=True)),
                ('relation_name', models.CharField(max_length=50)),
                ('relation_description', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='subRelationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_relation_type_id', models.IntegerField(unique=True)),
                ('sub_relation_name', models.CharField(max_length=50)),
                ('sub_relation_description', models.CharField(max_length=255)),
                ('relationType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.relationtype')),
            ],
        ),
        migrations.CreateModel(
            name='textMeta',
            fields=[
                ('text_uri', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title_ar', models.CharField(max_length=255)),
                ('title_lat', models.CharField(max_length=255)),
                ('text_type', models.CharField(blank=True, max_length=10)),
                ('tags', models.CharField(max_length=255)),
                ('author_uri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', related_query_name='text', to='api.authormeta')),
            ],
        ),
        migrations.CreateModel(
            name='versionMeta',
            fields=[
                ('version_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('version_uri', models.CharField(max_length=100)),
                ('char_length', models.IntegerField(null=True)),
                ('tok_length', models.IntegerField(null=True)),
                ('url', models.CharField(max_length=255)),
                ('editor', models.CharField(blank=True, max_length=100)),
                ('editor_place', models.CharField(blank=True, max_length=100)),
                ('publisher', models.CharField(blank=True, max_length=100)),
                ('edition_date', models.CharField(blank=True, max_length=100)),
                ('ed_info', models.CharField(blank=True, max_length=255)),
                ('version_lang', models.CharField(max_length=3, null=True)),
                ('tags', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=3)),
                ('annotation_status', models.CharField(max_length=50, null=True)),
                ('text_uri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', related_query_name='version', to='api.textmeta')),
            ],
        ),
        migrations.CreateModel(
            name='textRelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id1', models.CharField(max_length=50)),
                ('Id2', models.CharField(max_length=50)),
                ('relationType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.relationtype')),
                ('subRelationType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.subrelationtype')),
            ],
        ),
        migrations.CreateModel(
            name='authorName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=3, null=True)),
                ('shuhra', models.CharField(blank=True, max_length=255)),
                ('kunya', models.CharField(blank=True, max_length=255)),
                ('ism', models.CharField(blank=True, max_length=255)),
                ('laqab', models.CharField(blank=True, max_length=255)),
                ('nisba', models.CharField(blank=True, max_length=255)),
                ('author_uri', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='authornames', related_query_name='authorname', to='api.authormeta')),
            ],
        ),
    ]
