# Generated by Django 5.2 on 2026-02-24 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="A2BRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("authority", models.CharField(blank=True, max_length=100)),
                ("confidence", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RelationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=10)),
                ("subtype_code", models.CharField(blank=True, max_length=10)),
                ("name", models.CharField(blank=True, max_length=50)),
                ("name_inverted", models.CharField(blank=True, max_length=50)),
                ("descr", models.CharField(blank=True, max_length=255)),
                ("entities", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ReleaseInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("release_code", models.CharField(max_length=10)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("zenodo_link", models.CharField(blank=True, max_length=200)),
                ("release_notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_uri", models.CharField(max_length=50)),
                ("tags", models.CharField(blank=True, max_length=255)),
                ("bibliography", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "related_persons",
                    models.ManyToManyField(
                        related_name="persons_related",
                        related_query_name="person_related",
                        through="api.A2BRelation",
                        through_fields=("person_a", "person_b"),
                        to="api.author",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="a2brelation",
            name="person_a",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="related_persons_a",
                related_query_name="related_person_a",
                to="api.author",
            ),
        ),
        migrations.AddField(
            model_name="a2brelation",
            name="person_b",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="related_persons_b",
                related_query_name="related_person_b",
                to="api.author",
            ),
        ),
        migrations.AddField(
            model_name="a2brelation",
            name="relation_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.relationtype",
            ),
        ),
    ]
