# Generated by Django 3.2.5 on 2021-08-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=10, unique=True)),
                ('book_uri', models.CharField(max_length=100)),
                ('char_length', models.IntegerField()),
                ('token_length', models.IntegerField()),
                ('date', models.IntegerField()),
                ('book_title_ar', models.CharField(max_length=255)),
                ('book_title_lat', models.CharField(max_length=255)),
                ('version_uri', models.CharField(max_length=100)),
                ('book_text_url', models.CharField(max_length=255)),
            ],
        ),
    ]
