# Generated by Django 5.2 on 2026-02-25 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="DateType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("label", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Date",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_str", models.CharField(blank=True, max_length=255)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("month", models.IntegerField(blank=True, null=True)),
                ("day", models.IntegerField(blank=True, null=True)),
                (
                    "precision",
                    models.CharField(
                        choices=[
                            ("day", "Day"),
                            ("month", "Month"),
                            ("year", "Year"),
                            ("text", "Text/Unparsed"),
                        ],
                        default="day",
                        max_length=10,
                    ),
                ),
                ("ce_start", models.DateField(blank=True, db_index=True, null=True)),
                ("ce_end", models.DateField(blank=True, db_index=True, null=True)),
                ("source", models.CharField(blank=True, max_length=255)),
                ("confidence", models.IntegerField(blank=True, null=True)),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dates",
                        to="api.calendar",
                    ),
                ),
                (
                    "date_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dates",
                        to="api.datetype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DateLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_preferred", models.BooleanField(default=False)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="date_links",
                        to="api.author",
                    ),
                ),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="api.date",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="author",
            name="dates",
            field=models.ManyToManyField(
                blank=True,
                related_name="authors",
                through="api.DateLink",
                through_fields=("author", "date"),
                to="api.date",
            ),
        ),
        migrations.AddIndex(
            model_name="datelink",
            index=models.Index(
                fields=["author"], name="api_datelin_author__8aef0d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="datelink",
            constraint=models.CheckConstraint(
                condition=models.Q(("author__isnull", False)),
                name="date_exactly_one_target_author_text_edition",
            ),
        ),
    ]
