# Generated by Django 3.2.6 on 2023-07-06 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a2brelation',
            name='person_a_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_persons_a', related_query_name='related_person_a', to='api.authormeta'),
        ),
        migrations.AlterField(
            model_name='a2brelation',
            name='person_b_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_persons_b', related_query_name='related_person_b', to='api.authormeta'),
        ),
        migrations.AlterField(
            model_name='a2brelation',
            name='place_a_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_places_a', related_query_name='related_place_a', to='api.placemeta'),
        ),
        migrations.AlterField(
            model_name='a2brelation',
            name='place_b_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_places_b', related_query_name='related_place_b', to='api.placemeta'),
        ),
        migrations.AlterField(
            model_name='a2brelation',
            name='text_a_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_texts_a', related_query_name='related_text_a', to='api.textmeta'),
        ),
        migrations.AlterField(
            model_name='a2brelation',
            name='text_b_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_texts_b', related_query_name='related_text_b', to='api.textmeta'),
        ),
        migrations.AlterField(
            model_name='textmeta',
            name='related_texts',
            field=models.ManyToManyField(related_name='_api_textmeta_related_texts_+', related_query_name='text_related', through='api.a2bRelation', to='api.textMeta'),
        ),
    ]
