# Generated by Django 3.2.5 on 2021-08-01 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_text_url',
            new_name='title_ar',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_title_ar',
            new_name='title_lat',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='token_length',
            new_name='tok_length',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_title_lat',
            new_name='url',
        ),
    ]
