# Generated by Django 3.2.6 on 2022-08-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authormeta',
            name='author_ar_norm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='authormeta',
            name='author_lat_norm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='textmeta',
            name='title_ar_norm',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='textmeta',
            name='title_lat_norm',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
