# Generated by Django 3.2.6 on 2023-07-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230727_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='textreusestats',
            name='tsv_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
