# Generated by Django 3.2.6 on 2023-07-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230729_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpusinsights',
            name='number_of_completed_versions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corpusinsights',
            name='number_of_markdown_versions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corpusinsights',
            name='number_of_pri_versions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corpusinsights',
            name='number_of_sec_versions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
