# Generated by Django 5.2 on 2026-02-25 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_calendar_datetype_date_datelink_author_dates_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("normalized_name", models.CharField(max_length=255)),
                ("language", models.CharField(blank=True, db_index=True, max_length=3)),
                (
                    "name_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'shuhra', 'nisba', 'official', 'variant', 'short'",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["language", "name"],
                        name="api_objectn_languag_89460b_idx",
                    ),
                    models.Index(fields=["name"], name="api_objectn_name_7a7db1_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ObjectNameLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_preferred",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the preferred name of the object?",
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=255)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="object_name_links",
                        to="api.author",
                    ),
                ),
                (
                    "object_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="api.objectname",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="author",
            name="names",
            field=models.ManyToManyField(
                blank=True,
                related_name="authors",
                through="api.ObjectNameLink",
                through_fields=("author", "object_name"),
                to="api.objectname",
            ),
        ),
        migrations.AddIndex(
            model_name="objectnamelink",
            index=models.Index(
                fields=["author"], name="api_objectn_author__c17aa2_idx"
            ),
        ),
    ]
