# Generated by Django 3.2.6 on 2023-08-01 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_version_part_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='part_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.version'),
        ),
    ]
