# Generated by Django 3.2.5 on 2021-08-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210801_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.CharField(max_length=4),
        ),
    ]
