# Generated by Django 3.2.6 on 2023-07-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230731_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcecollectiondetails',
            name='affiliation',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
