# Generated by Django 3.2.6 on 2023-07-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230705_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placemeta',
            old_name='coordinates',
            new_name='coordinates_str',
        ),
    ]
