# Generated by Django 5.2 on 2026-02-26 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_objectname_objectnamelink_author_names_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("label", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="TextTypeLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_preferred", models.BooleanField(default=False)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("source", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_uri", models.CharField(max_length=100, unique=True)),
                ("tags", models.CharField(blank=True, max_length=255)),
                ("bibliography", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "authors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="texts",
                        through="api.A2BRelation",
                        through_fields=("text_b", "person_a"),
                        to="api.author",
                    ),
                ),
                (
                    "dates",
                    models.ManyToManyField(
                        blank=True,
                        related_name="texts",
                        through="api.DateLink",
                        through_fields=("text", "date"),
                        to="api.date",
                    ),
                ),
                (
                    "related_persons",
                    models.ManyToManyField(
                        related_name="related_texts",
                        related_query_name="related_text",
                        through="api.A2BRelation",
                        through_fields=("text_a", "person_b"),
                        to="api.author",
                    ),
                ),
                (
                    "related_texts",
                    models.ManyToManyField(
                        related_name="texts_related",
                        related_query_name="text_related",
                        through="api.A2BRelation",
                        through_fields=("text_a", "text_b"),
                        to="api.text",
                    ),
                ),
                (
                    "titles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="texts",
                        through="api.ObjectNameLink",
                        through_fields=("text", "object_name"),
                        to="api.objectname",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="a2brelation",
            name="text_a",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="related_texts_a",
                related_query_name="related_text_a",
                to="api.text",
            ),
        ),
        migrations.AddField(
            model_name="a2brelation",
            name="text_b",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="related_texts_b",
                related_query_name="related_text_b",
                to="api.text",
            ),
        ),
        migrations.AddField(
            model_name="datelink",
            name="text",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="date_links",
                to="api.text",
            ),
        ),
        migrations.AddField(
            model_name="objectnamelink",
            name="text",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="object_name_links",
                to="api.text",
            ),
        ),
        migrations.AddIndex(
            model_name="datelink",
            index=models.Index(fields=["text"], name="api_datelin_text_id_043358_idx"),
        ),
        migrations.AddIndex(
            model_name="objectnamelink",
            index=models.Index(fields=["text"], name="api_objectn_text_id_ac3b87_idx"),
        ),
        migrations.AddField(
            model_name="texttypelink",
            name="text",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="text_type_links",
                to="api.text",
            ),
        ),
        migrations.AddField(
            model_name="texttypelink",
            name="text_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links",
                to="api.texttype",
            ),
        ),
        migrations.AddField(
            model_name="text",
            name="text_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="texts",
                through="api.TextTypeLink",
                through_fields=("text", "text_type"),
                to="api.texttype",
            ),
        ),
        migrations.AddIndex(
            model_name="texttypelink",
            index=models.Index(
                fields=["text_type"], name="api_texttyp_text_ty_6d27de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="texttypelink",
            index=models.Index(fields=["text"], name="api_texttyp_text_id_e80ce9_idx"),
        ),
    ]
