# Generated by Django 3.2.6 on 2023-07-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_textreusestats_tsv_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='authormeta',
            name='bibliography',
            field=models.TextField(blank=True),
        ),
    ]
