# Generated by Django 3.2.6 on 2023-07-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_coordinates_placemeta_coordinates_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmeta',
            name='related_texts',
            field=models.ManyToManyField(related_name='texts_related', related_query_name='text_related', through='api.a2bRelation', to='api.textMeta'),
        ),
    ]
