# Generated by Django 3.2.6 on 2021-12-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210801_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_authors', models.IntegerField(null=True)),
                ('number_of_unique_authors', models.IntegerField(null=True)),
                ('number_of_books', models.IntegerField(null=True)),
                ('number_of_unique_books', models.IntegerField(null=True)),
            ],
        ),
    ]
