# Generated by Django 3.2.6 on 2023-07-31 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sourcecollectiondetails_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='versionmeta',
            name='source_coll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='versions', related_query_name='version', to='api.sourcecollectiondetails'),
        ),
    ]
