# Generated by Django 5.2 on 2026-02-26 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_texttype_texttypelink_text_a2brelation_text_a_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=50)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("url", models.CharField(blank=True, max_length=255)),
                ("affiliation", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="SourceCollectionDetails",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("url", models.CharField(blank=True, max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("affiliation", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_code", models.CharField(max_length=50)),
                (
                    "version_uri",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                ("page_range", models.CharField(blank=True, max_length=50)),
                ("language", models.CharField(blank=True, max_length=9)),
                (
                    "part_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="parts",
                        related_query_name="part",
                        to="api.version",
                    ),
                ),
                (
                    "source_coll",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="versions",
                        related_query_name="version",
                        to="api.sourcecollectiondetails",
                    ),
                ),
                (
                    "text",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="versions",
                        related_query_name="version",
                        to="api.text",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReleaseVersion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("char_length", models.IntegerField(blank=True, null=True)),
                ("tok_length", models.IntegerField(blank=True, null=True)),
                ("url", models.CharField(blank=True, max_length=255)),
                (
                    "analysis_priority",
                    models.CharField(
                        blank=True,
                        help_text="Primary or secondary text? Use 'pri' or 'sec'",
                        max_length=3,
                    ),
                ),
                (
                    "annotation_status",
                    models.CharField(
                        blank=True,
                        help_text="Extension of the file, indicating how far it has been annotated: inProgress, completed, mARkdown",
                        max_length=50,
                    ),
                ),
                (
                    "line_model",
                    models.CharField(
                        blank=True,
                        help_text="line recognition model used for OCR",
                        max_length=50,
                    ),
                ),
                (
                    "region_model",
                    models.CharField(
                        blank=True,
                        help_text="region recognition model used for OCR",
                        max_length=50,
                    ),
                ),
                (
                    "recognition_model",
                    models.CharField(
                        blank=True,
                        help_text="character recognition/transcription model used for OCR",
                        max_length=50,
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "contributors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="release_versions",
                        related_query_name="release_version",
                        to="api.contributor",
                    ),
                ),
                (
                    "release_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.releaseinfo",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="release_versions",
                        related_query_name="release_version",
                        to="api.version",
                    ),
                ),
            ],
        ),
    ]
