# Generated by Django 3.2.6 on 2023-07-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_authormeta_bibliography'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmeta',
            name='bibliography',
            field=models.TextField(blank=True),
        ),
    ]
