# Generated by Django 5.2 on 2026-02-26 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_contributor_sourcecollectiondetails_version_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Edition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("editor", models.CharField(blank=True, max_length=100)),
                ("edition_place", models.CharField(blank=True, max_length=100)),
                ("publisher", models.CharField(blank=True, max_length=100)),
                ("ed_info", models.CharField(blank=True, max_length=255)),
                ("pdf_url", models.CharField(blank=True, max_length=255)),
                (
                    "dates",
                    models.ManyToManyField(
                        blank=True,
                        related_name="editions",
                        through="api.DateLink",
                        through_fields=("edition", "date"),
                        to="api.date",
                    ),
                ),
                (
                    "text",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="editions",
                        related_query_name="edition",
                        to="api.text",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="a2brelation",
            name="edition_a",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="related_editions_a",
                related_query_name="related_edition_a",
                to="api.edition",
            ),
        ),
        migrations.AddField(
            model_name="a2brelation",
            name="edition_b",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="related_editions_b",
                related_query_name="related_edition_b",
                to="api.edition",
            ),
        ),
        migrations.AddField(
            model_name="datelink",
            name="edition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="date_links",
                to="api.edition",
            ),
        ),
        migrations.AddField(
            model_name="version",
            name="edition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="versions",
                related_query_name="version",
                to="api.edition",
            ),
        ),
        migrations.AddIndex(
            model_name="datelink",
            index=models.Index(
                fields=["edition"], name="api_datelin_edition_f9a174_idx"
            ),
        ),
    ]
