# Generated by Django 3.2.6 on 2021-12-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_aggregatedstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatedstats',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
