# Generated by Django 3.2.6 on 2023-07-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_corpusstats_textreusestats'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpusInsights',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_unique_authors', models.IntegerField(blank=True, null=True)),
                ('number_of_books', models.IntegerField(blank=True, null=True)),
                ('number_of_unique_versions', models.IntegerField(blank=True, null=True)),
                ('total_word_count', models.IntegerField(blank=True, null=True)),
                ('largest_book', models.IntegerField(blank=True, null=True)),
                ('total_word_count_pri', models.IntegerField(blank=True, null=True)),
                ('top_10_book_by_word_count', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AggregatedStats',
        ),
        migrations.AddField(
            model_name='textreusestats',
            name='book1_match_book2_per',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='textreusestats',
            name='book2_match_book1_per',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
