# Generated by Django 3.2.6 on 2023-08-04 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_version_part_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubIssueLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='GitHubIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('state', models.CharField(max_length=6)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='github_issues', related_query_name='github_issue', to='api.author')),
                ('labels', models.ManyToManyField(blank=True, null=True, related_name='github_issues', related_query_name='github_issue', to='api.GitHubIssueLabel')),
                ('text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='github_issues', related_query_name='github_issue', to='api.text')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='github_issues', related_query_name='github_issue', to='api.releaseversion')),
            ],
        ),
    ]
