# Generated by Django 3.2.6 on 2023-07-31 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_versionmeta_source_coll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corpusinsights',
            old_name='top_10_book_by_word_count',
            new_name='largest_10_books',
        ),
        migrations.RenameField(
            model_name='corpusinsights',
            old_name='number_of_unique_authors',
            new_name='number_of_authors',
        ),
    ]
