# Generated by Django 5.2 on 2026-02-27 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_edition_a2brelation_edition_a_a2brelation_edition_b_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edition",
            name="text",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="editions",
                related_query_name="edition",
                to="api.text",
            ),
        ),
        migrations.CreateModel(
            name="ManuscriptHolding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loc_uri", models.CharField(max_length=50)),
                ("notes", models.TextField(blank=True)),
                (
                    "names",
                    models.ManyToManyField(
                        blank=True,
                        related_name="manuscript_holdings",
                        through="api.ObjectNameLink",
                        through_fields=("manuscript_holding", "object_name"),
                        to="api.objectname",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="objectnamelink",
            name="manuscript_holding",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="object_name_links",
                to="api.manuscriptholding",
            ),
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coordinates_str", models.CharField(blank=True, max_length=50)),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "lon",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("country_code", models.CharField(blank=True, max_length=4)),
                (
                    "names",
                    models.ManyToManyField(
                        blank=True,
                        related_name="places",
                        through="api.ObjectNameLink",
                        through_fields=("place", "object_name"),
                        to="api.objectname",
                    ),
                ),
                (
                    "related_places",
                    models.ManyToManyField(
                        related_name="places_related",
                        related_query_name="place_related",
                        through="api.A2BRelation",
                        through_fields=("place_a", "place_b"),
                        to="api.place",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="manuscriptholding",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="city_manuscript_holdings",
                to="api.place",
            ),
        ),
        migrations.AddField(
            model_name="manuscriptholding",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="country_manuscript_holdings",
                to="api.place",
            ),
        ),
        migrations.AddField(
            model_name="a2brelation",
            name="place_a",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="related_places_a",
                related_query_name="related_place_a",
                to="api.place",
            ),
        ),
        migrations.AddField(
            model_name="a2brelation",
            name="place_b",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="related_places_b",
                related_query_name="related_place_b",
                to="api.place",
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="related_places",
            field=models.ManyToManyField(
                related_name="related_persons",
                related_query_name="related_person",
                through="api.A2BRelation",
                through_fields=("person_a", "place_b"),
                to="api.place",
            ),
        ),
        migrations.AddField(
            model_name="objectnamelink",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="object_name_links",
                to="api.place",
            ),
        ),
        migrations.AddField(
            model_name="text",
            name="related_places",
            field=models.ManyToManyField(
                related_name="related_texts",
                related_query_name="related_text",
                through="api.A2BRelation",
                through_fields=("text_a", "place_b"),
                to="api.place",
            ),
        ),
        migrations.AddIndex(
            model_name="objectnamelink",
            index=models.Index(fields=["place"], name="api_objectn_place_i_bb2c14_idx"),
        ),
        migrations.AddIndex(
            model_name="objectnamelink",
            index=models.Index(
                fields=["manuscript_holding"], name="api_objectn_manuscr_39c364_idx"
            ),
        ),
    ]
