# Generated by Django 3.2.6 on 2021-12-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_aggregatedstats_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_lat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='aggregatedstats',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
