# Generated by Django 3.2.6 on 2023-08-04 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_githubissue_githubissuelabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubissue',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='github_issues', related_query_name='github_issue', to='api.GitHubIssueLabel'),
        ),
        migrations.AlterField(
            model_name='githubissue',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='github_issues', related_query_name='github_issue', to='api.version'),
        ),
    ]
