# Generated by Django 3.2.6 on 2023-07-07 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20230706_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corpusinsights',
            old_name='number_of_unique_versions',
            new_name='number_of_versions',
        ),
    ]
