# Generated by Django 3.2.6 on 2023-07-31 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20230731_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corpusinsights',
            old_name='release',
            new_name='release_info',
        ),
    ]
