# Generated by Django 3.2.6 on 2023-07-07 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_number_of_unique_versions_corpusinsights_number_of_versions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseMeta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('release_code', models.CharField(max_length=10)),
                ('char_length', models.IntegerField(blank=True, null=True)),
                ('tok_length', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('analysis_priority', models.CharField(blank=True, max_length=3)),
                ('annotation_status', models.CharField(blank=True, max_length=50)),
                ('version_uri', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='releases', related_query_name='release', to='api.versionmeta')),
            ],
        ),
    ]
