# Generated by Django 3.2.6 on 2021-12-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211203_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregatedstats',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
