# Generated by Django 3.2.6 on 2023-08-04 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20230804_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubissue',
            old_name='author',
            new_name='about_author',
        ),
        migrations.RenameField(
            model_name='githubissue',
            old_name='text',
            new_name='about_text',
        ),
        migrations.RenameField(
            model_name='githubissue',
            old_name='version',
            new_name='about_version',
        ),
    ]
