# Generated by Django 5.2 on 2026-02-27 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_edition_text_manuscriptholding_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Script",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubCorpus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="place",
            name="code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="releaseversion",
            name="uncorrected_ocr",
            field=models.BooleanField(
                default=False,
                help_text="Was this version generated by OCR and not manually corrected?",
            ),
        ),
        migrations.CreateModel(
            name="LanguageScriptCombo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=3)),
                ("name", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="language_script_combo",
                        to="api.language",
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="language_script_combo",
                        to="api.script",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="version",
            name="language_script_combo",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="versions",
                related_query_name="version",
                to="api.languagescriptcombo",
            ),
        ),
        migrations.AddField(
            model_name="releaseversion",
            name="subcorpus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="release_versions",
                to="api.subcorpus",
            ),
        ),
    ]
