# Generated by Django 3.2.6 on 2023-07-07 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_releasemeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasemeta',
            name='version_uri',
        ),
    ]
