# Generated by Django 3.2.6 on 2021-12-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_aggregatedstats_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregatedstats',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
