# Generated by Django 3.2.6 on 2023-10-24 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230804_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionwiseReuseStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('n_instances', models.IntegerField(blank=True, null=True)),
                ('n_versions', models.IntegerField(blank=True, null=True)),
                ('release_version', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='versionwise_reuse_stats', related_query_name='versionwise_reuse', to='api.releaseversion')),
            ],
        ),
    ]
