# Generated by Django 5.2 on 2026-03-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_language_script_subcorpus_place_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="language_script_combo",
            field=models.ManyToManyField(
                blank=True,
                related_name="versions",
                related_query_name="version",
                to="api.languagescriptcombo",
            ),
        ),
    ]
