# Generated by Django 5.2 on 2026-03-02 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_version_language_script_combo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="version",
            name="page_range",
        ),
        migrations.AddField(
            model_name="releaseversion",
            name="page_range",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name="Manuscript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manuscript_uri", models.CharField(max_length=50)),
                ("tags", models.CharField(blank=True, max_length=255)),
                ("bibliography", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "dates",
                    models.ManyToManyField(
                        blank=True,
                        related_name="manuscripts",
                        through="api.DateLink",
                        through_fields=("manuscript", "date"),
                        to="api.date",
                    ),
                ),
                (
                    "manuscript_holding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="manuscripts",
                        related_query_name="manuscript",
                        to="api.manuscriptholding",
                    ),
                ),
                (
                    "manuscript_types",
                    models.ManyToManyField(
                        blank=True,
                        related_name="manuscripts",
                        through="api.TextTypeLink",
                        through_fields=("manuscript", "text_type"),
                        to="api.texttype",
                    ),
                ),
                (
                    "related_manuscripts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="manuscripts_related",
                        through="api.A2BRelation",
                        through_fields=("manuscript_a", "manuscript_b"),
                        to="api.manuscript",
                    ),
                ),
                (
                    "related_persons",
                    models.ManyToManyField(
                        blank=True,
                        related_name="manuscripts",
                        through="api.A2BRelation",
                        through_fields=("manuscript_b", "person_a"),
                        to="api.author",
                    ),
                ),
                (
                    "related_places",
                    models.ManyToManyField(
                        blank=True,
                        related_name="manuscripts",
                        through="api.A2BRelation",
                        through_fields=("manuscript_a", "place_b"),
                        to="api.place",
                    ),
                ),
                (
                    "related_texts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="manuscripts",
                        through="api.A2BRelation",
                        through_fields=("manuscript_a", "text_b"),
                        to="api.text",
                    ),
                ),
                (
                    "titles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="manuscripts",
                        through="api.ObjectNameLink",
                        through_fields=("manuscript", "object_name"),
                        to="api.objectname",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="a2brelation",
            name="manuscript_a",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="related_manuscripts_a",
                related_query_name="related_manuscript_a",
                to="api.manuscript",
            ),
        ),
        migrations.AddField(
            model_name="a2brelation",
            name="manuscript_b",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="related_manuscripts_b",
                related_query_name="related_manuscript_b",
                to="api.manuscript",
            ),
        ),
        migrations.AddField(
            model_name="datelink",
            name="manuscript",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="date_links",
                to="api.manuscript",
            ),
        ),
        migrations.AddField(
            model_name="objectnamelink",
            name="manuscript",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="object_name_links",
                to="api.manuscript",
            ),
        ),
        migrations.AddField(
            model_name="texttypelink",
            name="manuscript",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="text_type_links",
                to="api.manuscript",
            ),
        ),
        migrations.AddField(
            model_name="version",
            name="manuscript",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="transcriptions",
                related_query_name="transcription",
                to="api.manuscript",
            ),
        ),
        migrations.AddIndex(
            model_name="datelink",
            index=models.Index(
                fields=["manuscript"], name="api_datelin_manuscr_955e5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="objectnamelink",
            index=models.Index(
                fields=["manuscript"], name="api_objectn_manuscr_736155_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="texttypelink",
            index=models.Index(
                fields=["manuscript"], name="api_texttyp_manuscr_220ec1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="texttypelink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("text__isnull", False), ("manuscript__isnull", True)),
                    models.Q(("text__isnull", True), ("manuscript__isnull", False)),
                    _connector="OR",
                ),
                name="texttype_exactly_one_target",
            ),
        ),
    ]
