# Generated by Django 3.2.6 on 2021-12-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_aggregatedstats_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_ar',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
