# Generated by Django 3.2.6 on 2023-07-07 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_releasemeta_version_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasemeta',
            name='version_uri',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='releases', related_query_name='release', to='api.versionmeta'),
            preserve_default=False,
        ),
    ]
