# Generated by Django 3.2.6 on 2023-07-08 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_releasemeta_version_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textreusestats',
            name='book_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textreuse_b1', related_query_name='textreuse_b1', to='api.versionmeta', to_field='version_id'),
        ),
        migrations.AlterField(
            model_name='textreusestats',
            name='book_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textreuse_b2', related_query_name='textreuse_b2', to='api.versionmeta', to_field='version_id'),
        ),
    ]
