# Generated by Django 5.2 on 2026-03-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_remove_version_page_range_releaseversion_page_range_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manuscript",
            name="related_manuscripts",
            field=models.ManyToManyField(
                blank=True,
                related_name="manuscripts_related",
                related_query_name="manuscript_related",
                through="api.A2BRelation",
                through_fields=("manuscript_a", "manuscript_b"),
                to="api.manuscript",
            ),
        ),
    ]
