# Generated by Django 5.2 on 2026-03-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_manuscript_related_manuscripts"),
    ]

    operations = [
        migrations.AddField(
            model_name="a2brelation",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="binding",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="catalog_reference",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="colophon",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="columns",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="decoration",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="explicit",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="hands",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="height",
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="incipit",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="ink",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="lines_per_page",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="script",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="shelfmark",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="stamps",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="volumes",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="width",
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="manuscript_uri",
            field=models.CharField(max_length=100),
        ),
    ]
