# Generated by Django 3.2.6 on 2023-07-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20230708_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('release_code', models.CharField(max_length=10)),
                ('release_date', models.DateField()),
                ('zenodo_link', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SourceCollectionDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='authormeta',
            name='author_ar_prefered',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='authormeta',
            name='author_lat_prefered',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='authormeta',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='textmeta',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='textmeta',
            name='title_ar_prefered',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='textmeta',
            name='title_lat_prefered',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='versionmeta',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
