# Generated by Django 5.2 on 2026-03-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_a2brelation_notes_manuscript_binding_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="language",
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
