# Generated by Django 3.2.6 on 2021-12-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20211208_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='annotation_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
