# Generated by Django 5.2 on 2026-03-03 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_version_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="IdentifierProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("base_url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExternalIDLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_id_links",
                        to="api.author",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_id_links",
                        to="api.edition",
                    ),
                ),
                (
                    "identifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="api.externalid",
                    ),
                ),
                (
                    "manuscript",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_id_links",
                        to="api.manuscript",
                    ),
                ),
                (
                    "manuscript_holding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_id_links",
                        to="api.manuscriptholding",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_id_links",
                        to="api.place",
                    ),
                ),
                (
                    "text",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_id_links",
                        to="api.text",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_id_links",
                        to="api.version",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="author",
            name="external_ids",
            field=models.ManyToManyField(
                blank=True,
                related_name="authors",
                through="api.ExternalIDLink",
                through_fields=("author", "identifier"),
                to="api.externalid",
            ),
        ),
        migrations.AddField(
            model_name="edition",
            name="external_ids",
            field=models.ManyToManyField(
                blank=True,
                related_name="editions",
                through="api.ExternalIDLink",
                through_fields=("edition", "identifier"),
                to="api.externalid",
            ),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="external_ids",
            field=models.ManyToManyField(
                blank=True,
                related_name="manuscripts",
                through="api.ExternalIDLink",
                through_fields=("manuscript", "identifier"),
                to="api.externalid",
            ),
        ),
        migrations.AddField(
            model_name="manuscriptholding",
            name="external_ids",
            field=models.ManyToManyField(
                blank=True,
                related_name="manuscript_holdings",
                through="api.ExternalIDLink",
                through_fields=("manuscript_holding", "identifier"),
                to="api.externalid",
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="external_ids",
            field=models.ManyToManyField(
                blank=True,
                related_name="places",
                through="api.ExternalIDLink",
                through_fields=("place", "identifier"),
                to="api.externalid",
            ),
        ),
        migrations.AddField(
            model_name="text",
            name="external_ids",
            field=models.ManyToManyField(
                blank=True,
                related_name="texts",
                through="api.ExternalIDLink",
                through_fields=("text", "identifier"),
                to="api.externalid",
            ),
        ),
        migrations.AddField(
            model_name="version",
            name="external_ids",
            field=models.ManyToManyField(
                blank=True,
                related_name="versions",
                through="api.ExternalIDLink",
                through_fields=("version", "identifier"),
                to="api.externalid",
            ),
        ),
        migrations.AddField(
            model_name="externalid",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="external_ids",
                to="api.identifierprovider",
            ),
        ),
        migrations.AddIndex(
            model_name="externalidlink",
            index=models.Index(
                fields=["identifier"], name="api_externa_identif_250dda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="externalidlink",
            index=models.Index(
                fields=["author"], name="api_externa_author__bba8ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="externalidlink",
            index=models.Index(fields=["text"], name="api_externa_text_id_b5f7a6_idx"),
        ),
        migrations.AddIndex(
            model_name="externalidlink",
            index=models.Index(
                fields=["manuscript_holding"], name="api_externa_manuscr_3d5d50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="externalidlink",
            index=models.Index(fields=["place"], name="api_externa_place_i_51fbd1_idx"),
        ),
        migrations.AddIndex(
            model_name="externalidlink",
            index=models.Index(
                fields=["edition"], name="api_externa_edition_1cd0d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="externalidlink",
            index=models.Index(
                fields=["version"], name="api_externa_version_259bac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="externalidlink",
            index=models.Index(
                fields=["manuscript"], name="api_externa_manuscr_360594_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="externalidlink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("author__isnull", False),
                        ("text__isnull", True),
                        ("manuscript_holding__isnull", True),
                        ("place__isnull", True),
                        ("edition__isnull", True),
                        ("version__isnull", True),
                        ("manuscript__isnull", True),
                    ),
                    models.Q(
                        ("author__isnull", True),
                        ("text__isnull", False),
                        ("manuscript_holding__isnull", True),
                        ("place__isnull", True),
                        ("edition__isnull", True),
                        ("version__isnull", True),
                        ("manuscript__isnull", True),
                    ),
                    models.Q(
                        ("author__isnull", True),
                        ("text__isnull", True),
                        ("manuscript_holding__isnull", False),
                        ("place__isnull", True),
                        ("edition__isnull", True),
                        ("version__isnull", True),
                        ("manuscript__isnull", True),
                    ),
                    models.Q(
                        ("author__isnull", True),
                        ("text__isnull", True),
                        ("manuscript_holding__isnull", True),
                        ("place__isnull", False),
                        ("edition__isnull", True),
                        ("version__isnull", True),
                        ("manuscript__isnull", True),
                    ),
                    models.Q(
                        ("author__isnull", True),
                        ("text__isnull", True),
                        ("manuscript_holding__isnull", True),
                        ("place__isnull", True),
                        ("edition__isnull", False),
                        ("version__isnull", True),
                        ("manuscript__isnull", True),
                    ),
                    models.Q(
                        ("author__isnull", True),
                        ("text__isnull", True),
                        ("manuscript_holding__isnull", True),
                        ("place__isnull", True),
                        ("edition__isnull", True),
                        ("version__isnull", False),
                        ("manuscript__isnull", True),
                    ),
                    models.Q(
                        ("author__isnull", True),
                        ("text__isnull", True),
                        ("manuscript_holding__isnull", True),
                        ("place__isnull", True),
                        ("edition__isnull", True),
                        ("version__isnull", True),
                        ("manuscript__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="externalid_exactly_one_target",
            ),
        ),
        migrations.AddIndex(
            model_name="externalid",
            index=models.Index(
                fields=["provider", "external_id"],
                name="api_externa_provide_3dd35f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="externalid",
            index=models.Index(
                fields=["external_id"], name="api_externa_externa_5f5a3b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="externalid",
            constraint=models.UniqueConstraint(
                fields=("provider", "external_id"), name="uniq_provider_external_id"
            ),
        ),
    ]
