# Generated by Django 6.0 on 2026-03-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_externalid_identifierprovider_externalidlink_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="releaseversion",
            name="subcorpus",
            field=models.CharField(
                blank=True, help_text="Subcorpus (ara, per, mss)", max_length=25
            ),
        ),
    ]
