# Generated by Django 3.2.6 on 2022-03-24 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_book_annotation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='authorMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(max_length=10, unique=True)),
                ('author_uri', models.CharField(max_length=50, null=True)),
                ('date', models.CharField(max_length=4, null=True)),
                ('author_ar', models.CharField(max_length=255, null=True)),
                ('author_lat', models.CharField(max_length=255)),
                ('ism_ar', models.CharField(blank=True, max_length=255)),
                ('ism_lat', models.CharField(blank=True, max_length=255)),
                ('kunya_ar', models.CharField(blank=True, max_length=255)),
                ('kunya_lat', models.CharField(blank=True, max_length=255)),
                ('laqab_ar', models.CharField(blank=True, max_length=255)),
                ('laqab_lat', models.CharField(blank=True, max_length=255)),
                ('nisba_ar', models.CharField(blank=True, max_length=255)),
                ('nisba_lat', models.CharField(blank=True, max_length=255)),
                ('shuhra_ar', models.CharField(blank=True, max_length=255)),
                ('shuhra_lat', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='relationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type_id', models.IntegerField(unique=True)),
                ('relation_name', models.CharField(max_length=50)),
                ('relation_description', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='subRelationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_relation_type_id', models.IntegerField(unique=True)),
                ('sub_relation_name', models.CharField(max_length=50)),
                ('sub_relation_description', models.CharField(max_length=255)),
                ('relationType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.relationtype')),
            ],
        ),
        migrations.CreateModel(
            name='textMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_id', models.CharField(max_length=10, unique=True)),
                ('text_uri', models.CharField(max_length=100)),
                ('title_ar', models.CharField(max_length=255)),
                ('title_lat', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('authorMeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.authormeta')),
            ],
        ),
        migrations.CreateModel(
            name='textRelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textRelationID', models.IntegerField(unique=True)),
                ('verion1_Id', models.CharField(max_length=50)),
                ('verion2_Id', models.CharField(max_length=50)),
                ('relationType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.relationtype')),
                ('subRelationType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.subrelationtype')),
            ],
        ),
        migrations.CreateModel(
            name='versionMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_id', models.CharField(max_length=10, unique=True)),
                ('version_uri', models.CharField(max_length=100)),
                ('char_length', models.IntegerField(null=True)),
                ('tok_length', models.IntegerField(null=True)),
                ('url', models.CharField(max_length=255)),
                ('editor', models.CharField(blank=True, max_length=100)),
                ('editor_place', models.CharField(blank=True, max_length=100)),
                ('publisher', models.CharField(blank=True, max_length=100)),
                ('edition_date', models.CharField(blank=True, max_length=100)),
                ('tags', models.CharField(blank=True, max_length=100)),
                ('releases', models.CharField(blank=True, max_length=100)),
                ('textMeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.textmeta')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
