# Generated by Django 3.2.6 on 2022-03-24 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220324_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authormeta',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='textmeta',
            name='text_id',
        ),
    ]
