# Generated by Django 6.0 on 2026-03-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_releaseversion_subcorpus"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="iso_639_1",
            field=models.CharField(
                blank=True, help_text="2-letter language code", max_length=2
            ),
        ),
        migrations.AddField(
            model_name="language",
            name="iso_639_3",
            field=models.CharField(
                blank=True, help_text="3-letter language code", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="script",
            name="iso_15924",
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
