# Generated by Django 6.0 on 2026-03-18 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_language_iso_639_1_language_iso_639_3_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScriptType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="externalidlink",
            name="externalid_exactly_one_target",
        ),
        migrations.AddField(
            model_name="edition",
            name="manuscript",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="editions",
                related_query_name="edition",
                to="api.manuscript",
            ),
        ),
        migrations.AddField(
            model_name="manuscriptholding",
            name="catalogs",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="manuscriptholding",
            name="links",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="edition",
            name="pdf_url",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="scripttype",
            name="external_ids",
            field=models.ManyToManyField(
                blank=True,
                related_name="script_types",
                through="api.ExternalIDLink",
                through_fields=("script_type", "identifier"),
                to="api.externalid",
            ),
        ),
        migrations.AddField(
            model_name="scripttype",
            name="script",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="script_type",
                to="api.script",
            ),
        ),
        migrations.AddField(
            model_name="externalidlink",
            name="script_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="external_id_links",
                to="api.scripttype",
            ),
        ),
        migrations.AddIndex(
            model_name="externalidlink",
            index=models.Index(
                fields=["script_type"], name="api_externa_script__525660_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="externalidlink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("author__isnull", False),
                        ("text__isnull", True),
                        ("manuscript_holding__isnull", True),
                        ("place__isnull", True),
                        ("edition__isnull", True),
                        ("version__isnull", True),
                        ("manuscript__isnull", True),
                        ("script_type__isnull", True),
                    ),
                    models.Q(
                        ("author__isnull", True),
                        ("text__isnull", False),
                        ("manuscript_holding__isnull", True),
                        ("place__isnull", True),
                        ("edition__isnull", True),
                        ("version__isnull", True),
                        ("manuscript__isnull", True),
                        ("script_type__isnull", True),
                    ),
                    models.Q(
                        ("author__isnull", True),
                        ("text__isnull", True),
                        ("manuscript_holding__isnull", False),
                        ("place__isnull", True),
                        ("edition__isnull", True),
                        ("version__isnull", True),
                        ("manuscript__isnull", True),
                        ("script_type__isnull", True),
                    ),
                    models.Q(
                        ("author__isnull", True),
                        ("text__isnull", True),
                        ("manuscript_holding__isnull", True),
                        ("place__isnull", False),
                        ("edition__isnull", True),
                        ("version__isnull", True),
                        ("manuscript__isnull", True),
                        ("script_type__isnull", True),
                    ),
                    models.Q(
                        ("author__isnull", True),
                        ("text__isnull", True),
                        ("manuscript_holding__isnull", True),
                        ("place__isnull", True),
                        ("edition__isnull", False),
                        ("version__isnull", True),
                        ("manuscript__isnull", True),
                        ("script_type__isnull", True),
                    ),
                    models.Q(
                        ("author__isnull", True),
                        ("text__isnull", True),
                        ("manuscript_holding__isnull", True),
                        ("place__isnull", True),
                        ("edition__isnull", True),
                        ("version__isnull", False),
                        ("manuscript__isnull", True),
                        ("script_type__isnull", True),
                    ),
                    models.Q(
                        ("author__isnull", True),
                        ("text__isnull", True),
                        ("manuscript_holding__isnull", True),
                        ("place__isnull", True),
                        ("edition__isnull", True),
                        ("version__isnull", True),
                        ("manuscript__isnull", False),
                        ("script_type__isnull", True),
                    ),
                    models.Q(
                        ("author__isnull", True),
                        ("text__isnull", True),
                        ("manuscript_holding__isnull", True),
                        ("place__isnull", True),
                        ("edition__isnull", True),
                        ("version__isnull", True),
                        ("manuscript__isnull", True),
                        ("script_type__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="externalid_exactly_one_target",
            ),
        ),
    ]
