# Generated by Django 6.0 on 2026-03-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_scripttype_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="datelink",
            name="date_exactly_one_target_author_text_edition",
        ),
        migrations.AddConstraint(
            model_name="datelink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("author__isnull", False),
                        ("text__isnull", True),
                        ("edition__isnull", True),
                        ("manuscript__isnull", True),
                    ),
                    models.Q(
                        ("author__isnull", True),
                        ("text__isnull", False),
                        ("edition__isnull", True),
                        ("manuscript__isnull", True),
                    ),
                    models.Q(
                        ("author__isnull", True),
                        ("text__isnull", True),
                        ("edition__isnull", False),
                        ("manuscript__isnull", True),
                    ),
                    models.Q(
                        ("author__isnull", True),
                        ("text__isnull", True),
                        ("edition__isnull", True),
                        ("manuscript__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="date_exactly_one_target_author_text_edition",
            ),
        ),
    ]
