# Generated by Django 6.0 on 2026-03-18 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0018_remove_datelink_date_exactly_one_target_author_text_edition_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="edition",
            name="text",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="editions",
                related_query_name="edition",
                to="api.text",
            ),
        ),
    ]
