# Generated by Django 3.2.6 on 2022-03-25 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_versionmeta_annotation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authormeta',
            name='ism_ar',
        ),
        migrations.RemoveField(
            model_name='authormeta',
            name='ism_lat',
        ),
        migrations.RemoveField(
            model_name='authormeta',
            name='kunya_ar',
        ),
        migrations.RemoveField(
            model_name='authormeta',
            name='kunya_lat',
        ),
        migrations.RemoveField(
            model_name='authormeta',
            name='laqab_ar',
        ),
        migrations.RemoveField(
            model_name='authormeta',
            name='laqab_lat',
        ),
        migrations.RemoveField(
            model_name='authormeta',
            name='nisba_ar',
        ),
        migrations.RemoveField(
            model_name='authormeta',
            name='nisba_lat',
        ),
        migrations.RemoveField(
            model_name='authormeta',
            name='shuhra_ar',
        ),
        migrations.RemoveField(
            model_name='authormeta',
            name='shuhra_lat',
        ),
        migrations.AddField(
            model_name='authormeta',
            name='authorDateAH',
            field=models.IntegerField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='authormeta',
            name='authorDateCE',
            field=models.IntegerField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='authormeta',
            name='authorDateString',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='authorName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=3, null=True)),
                ('shuhra', models.CharField(blank=True, max_length=255)),
                ('kunya', models.CharField(blank=True, max_length=255)),
                ('ism', models.CharField(blank=True, max_length=255)),
                ('laqab', models.CharField(blank=True, max_length=255)),
                ('nisba', models.CharField(blank=True, max_length=255)),
                ('authorMeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.authormeta')),
            ],
        ),
    ]
