# Generated by Django 6.0 on 2026-03-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_edition_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendar",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name="objectname",
            index=models.Index(
                fields=["normalized_name"], name="api_objectn_normali_b5fef6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="objectnamelink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("author__isnull", False),
                        ("text__isnull", True),
                        ("manuscript__isnull", True),
                        ("manuscript_holding__isnull", True),
                        ("place__isnull", True),
                    ),
                    models.Q(
                        ("author__isnull", True),
                        ("text__isnull", False),
                        ("manuscript__isnull", True),
                        ("manuscript_holding__isnull", True),
                        ("place__isnull", True),
                    ),
                    models.Q(
                        ("author__isnull", True),
                        ("text__isnull", True),
                        ("manuscript__isnull", False),
                        ("manuscript_holding__isnull", True),
                        ("place__isnull", True),
                    ),
                    models.Q(
                        ("author__isnull", True),
                        ("text__isnull", True),
                        ("manuscript__isnull", True),
                        ("manuscript_holding__isnull", False),
                        ("place__isnull", True),
                    ),
                    models.Q(
                        ("author__isnull", True),
                        ("text__isnull", True),
                        ("manuscript__isnull", True),
                        ("manuscript_holding__isnull", True),
                        ("place__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="exactly_one_target_object",
            ),
        ),
    ]
