# Generated by Django 3.2.6 on 2022-03-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20220325_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormeta',
            name='authorDateAH',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='authormeta',
            name='authorDateCE',
            field=models.IntegerField(null=True),
        ),
    ]
