# Generated by Django 3.2.6 on 2022-03-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20220325_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormeta',
            name='date',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
