# Generated by Django 6.0 on 2026-03-24 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_calendar_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorpusInsights",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("number_of_authors", models.IntegerField(blank=True, null=True)),
                ("number_of_books", models.IntegerField(blank=True, null=True)),
                ("number_of_versions", models.IntegerField(blank=True, null=True)),
                (
                    "number_of_manuscript_holdings",
                    models.IntegerField(blank=True, null=True),
                ),
                ("number_of_manuscripts", models.IntegerField(blank=True, null=True)),
                ("number_of_pri_versions", models.IntegerField(blank=True, null=True)),
                ("number_of_sec_versions", models.IntegerField(blank=True, null=True)),
                (
                    "number_of_markdown_versions",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "number_of_completed_versions",
                    models.IntegerField(blank=True, null=True),
                ),
                ("total_word_count", models.IntegerField(blank=True, null=True)),
                ("total_word_count_pri", models.IntegerField(blank=True, null=True)),
                ("largest_book_size", models.IntegerField(blank=True, null=True)),
                ("largest_book", models.CharField(blank=True, max_length=100)),
                ("largest_10_books", models.JSONField(blank=True, null=True)),
                (
                    "release_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="corpus_statistics",
                        related_query_name="corpus_statistics",
                        to="api.releaseinfo",
                    ),
                ),
            ],
        ),
    ]
