# Generated by Django 6.0 on 2026-03-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_corpusinsights"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corpusinsights",
            name="number_of_completed_versions",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="corpusinsights",
            name="number_of_markdown_versions",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="corpusinsights",
            name="number_of_pri_versions",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="corpusinsights",
            name="number_of_sec_versions",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="corpusinsights",
            name="number_of_versions",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="corpusinsights",
            name="total_word_count",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="corpusinsights",
            name="total_word_count_pri",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
