# Generated by Django 3.2.6 on 2022-03-25 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_authormeta_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorname',
            name='authorMeta',
        ),
        migrations.AddField(
            model_name='authormeta',
            name='authorName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.authorname'),
        ),
    ]
