# Generated by Django 6.0 on 2026-03-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_alter_corpusinsights_number_of_completed_versions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="corpusinsights",
            name="subcorpora",
            field=models.JSONField(
                blank=True,
                help_text="List of subcorpus codes present in this release, e.g. ['ara', 'per', 'mss']",
                null=True,
            ),
        ),
    ]
