# Generated by Django 3.2.6 on 2022-03-25 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20220325_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authormeta',
            name='authorName',
        ),
        migrations.AddField(
            model_name='authorname',
            name='authorMeta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.authormeta'),
        ),
    ]
