# Generated by Django 6.0 on 2026-03-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_corpusinsights_subcorpora"),
    ]

    operations = [
        migrations.AddField(
            model_name="corpusinsights",
            name="has_manuscripts",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="corpusinsights",
            name="languages",
            field=models.JSONField(
                blank=True,
                help_text="List of all language codes present in this release, e.g. ['ara', 'per']",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="corpusinsights",
            name="subcorpora",
            field=models.JSONField(
                blank=True,
                help_text="List of subcorpus codes present in this release, e.g. ['ARA', 'PER', 'MSS']",
                null=True,
            ),
        ),
    ]
