# Generated by Django 6.0 on 2026-04-02 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_corpusinsights_has_manuscripts_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VersionwiseReuseStats",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("n_instances", models.IntegerField(blank=True, null=True)),
                ("n_versions", models.IntegerField(blank=True, null=True)),
                (
                    "release_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="versionwise_reuse_stats",
                        related_query_name="versionwise_reuse",
                        to="api.releaseversion",
                    ),
                ),
            ],
        ),
    ]
