# Generated by Django 6.0 on 2026-04-07 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_versionwisereusestats"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="objectname",
            unique_together={("name", "normalized_name", "language", "name_type")},
        ),
    ]
