# Generated by Django 3.2.6 on 2022-03-25 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_authorname_authormeta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorname',
            old_name='authorMeta',
            new_name='author_uri',
        ),
    ]
