# Generated by Django 3.2.6 on 2022-03-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_authorname_author_uri'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorname',
            old_name='author_uri',
            new_name='authorMeta',
        ),
    ]
