# Generated by Django 3.2.6 on 2022-03-25 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_versionmeta_textmeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorname',
            name='authorMeta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_names', to='api.authormeta'),
        ),
    ]
