# Generated by Django 3.2.6 on 2022-03-25 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_authorname_authormeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmeta',
            name='authorMeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', related_query_name='text', to='api.authormeta'),
        ),
    ]
