# Generated by Django 3.2.6 on 2022-03-25 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_versionmeta_textmeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionmeta',
            name='textMeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', related_query_name='version', to='api.textmeta'),
        ),
    ]
